/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deliveryvendor;

import java.awt.List;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DeliveryTask extends javax.swing.JPanel {
private VendorRunner user;
    /**
     * Creates new form DeliveryTask
     */
    String filePath = "resources/order.txt";
    int[] displayColumnIndices = {0,1,2,3,4,5,8,9,10};
    int[] displayindexCheck = {0,1,2,3,4,5,8,9,10,11};
    public String OrderID;
    public DeliveryTask(VendorRunner user) {
        initComponents();
        this.user = user;
        DeliveryTaskClass obj1 = new DeliveryTaskClass();
        
        try {            
            obj1.loadTableData(filePath, displayColumnIndices,(DefaultTableModel) TaskTable.getModel());
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(DeliveryTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        TaskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TaskTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TaskTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Task Overview");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TaskTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskTableMouseReleased
        // TODO add your handling code here:
        int row = TaskTable.getSelectedRow();        
        boolean TaskAssigned=false;
        DeliveryTaskClass obj2 = new DeliveryTaskClass();
        DefaultTableModel model = (DefaultTableModel)TaskTable.getModel();
        OrderID = String.valueOf(model.getValueAt(row,0));
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to accept this delivery task?",
                "TaskAssign",
                JOptionPane.YES_NO_OPTION);       
        
        if(result == JOptionPane.YES_OPTION){
            try {
                TaskAssigned = obj2.checkStatus(filePath,displayindexCheck,user.getId());
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(DeliveryTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            if (TaskAssigned) {                
                                       
                try {
                    String [] lines = obj2.readLines(filePath);
                    obj2.modifyAttribute(lines,9,9,OrderID,"delivery assigned");
                    obj2.writeLinesToFile(filePath, lines);
                    obj2.modifyAttribute(lines,12,11,OrderID,user.getId());
                    obj2.writeLinesToFile(filePath, lines);
                    System.out.println("Modification successful.");
                    model.setRowCount(0);
                    model.setColumnCount(0);                    
                    obj2.loadTableData(filePath, displayColumnIndices,(DefaultTableModel) TaskTable.getModel());
                    JOptionPane.showMessageDialog(this, "Task is assigned!");
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(DeliveryTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    
                }       
            } else {            
                JOptionPane.showMessageDialog(this,"You have already assigned 1 task, please complete the task before assigning another one.");
                
                
            }              
                
        }else{
                
        }
            
            
        
        
        
    }//GEN-LAST:event_TaskTableMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaskTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
